spring:
  application:
    name: finance_ai_agent

  datasource:
    url: jdbc:postgresql://localhost:5432/finance_ai_agent
    username: finance_user
    password: finance_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

server:
  port: 8080

app:
  knowledge:
    docs-path: docs/rag
    seed:
      enabled: false
      overwrite: false
      language: pt-BR
      audience: BEGINNER
jwt:
  secret: ${JWT_SECRET:secret-key-super-segura}