spring:
  application:
    name: finance_ai_agent 
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        completions-path: ${OPENAI_CHAT_COMPLETIONS_PATH}
        options:
          model: ${OPENAI_MODEL}
      embedding:
        embeddings-path: ${OPENAI_EMBEDDINGS_PATH}
        options:
          model: ${OPENAI_EMBEDDING_MODEL}
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        table-name: vector_store
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: ${DEEPSEEK_BASE_URL}
      chat:
        completions-path: ${DEEPSEEK_CHAT_COMPLETIONS_PATH}
        options:
          model: ${DEEPSEEK_MODEL_CHAT}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080

app:
  knowledge:
    docs-path: docs/rag
    seed:
      enabled: false
      overwrite: false
      language: pt-BR
      audience: BEGINNER
jwt:
  secret: ${JWT_SECRET:secret-key-super-segura}